hostname: gbf-proxy
server_dir: "/opt/gbf-proxy"
server_names:
  - proxy-a
  - proxy-b
haproxy_dir: "/etc/haproxy"
local_server_dir: "{{ playbook_dir }}/../server"
local_web_root: "{{ playbook_dir }}/www"

haproxy_cfg: "{{ haproxy_dir }}/haproxy.cfg"
haproxy_pid: "{{ haproxy_dir }}/haproxy.pid"
haproxy_cert: "{{ haproxy_dir }}/haproxy.pem"
haproxy_sock: "{{ haproxy_dir }}/admin.sock"

nginx_conf: "{{ server_dir }}/nginx.conf"
nginx_listen: "unix:{{ server_dir }}/web.sock"
nginx_pid: "{{ server_dir }}/nginx.pid"

web_root: "{{ server_dir }}/www"

memcached_mem_ratio: 0.75
