- name: Setting facts for supervisord
  set_fact:
    def_memcached_mem: "{{ (ansible_memtotal_mb * memcached_mem_ratio) | round | int }}"
- name: Generating supervisord configuration
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/conf.d/services.conf
    owner: root
    group: root
    mode: 0644
  register: supervisord_conf_result
