- name: Generating new HAProxy configuration
  template:
    src: "{{ init_templates }}/haproxy.cfg.j2"
    dest: "{{ haproxy_cfg }}"
    owner: haproxy
    group: haproxy
    mode: 0644
  register: haproxy_cfg_result
- block:
    - name: Getting HAProxy PID
      shell: supervisorctl pid haproxy
      changed_when: false
      register: haproxy_pid_sh
    - name: Reloading HAProxy configuration
      shell: >-
        /usr/sbin/haproxy -f {{ haproxy_cfg }} -c -q &&
        /bin/kill -USR2 {{ haproxy_pid_sh.stdout }}
  when: haproxy_cfg_result.changed
