- name: Running common HAProxy tasks
  include_role:
    name: common
    tasks_from: haproxy
- block:
    - name: Getting HAProxy PID
      shell: supervisorctl pid haproxy
      changed_when: false
      register: haproxy_pid_sh
    - name: Reloading HAProxy configuration
      shell: >-
        /usr/sbin/haproxy -f {{ haproxy_cfg }} -c -q &&
        /bin/kill -USR2 {{ haproxy_pid_sh.stdout }}
  when: haproxy_cfg_result.changed
