- name: Running common supervisord tasks
  include_role:
    name: common
    tasks_from: supervisord
- name: Reloading supervisord configuration
  shell: supervisorctl reload
  when: supervisord_conf_result.changed
