language: go
services:
  - redis-server
go:
  - "1.11"
env:
  - DEP_VERSION="0.5.0"
before_install:
  - curl -fsSL https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - bash scripts/install.sh
script:
  - bash scripts/test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
