language: go
go:
  - "1.10"
env:
  - DEP_VERSION="0.5.0"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - bash install.sh
script:
  - bash test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)