- name: Setting certbot facts
  set_fact:
    live_certs: "/etc/letsencrypt/live/{{ hostname }}"
    renew_script_path: "{{ server_dir }}/renew-cert.sh"
- name: Installing certbot
  apt:
    name: certbot
    state: latest
    update_cache: yes
    cache_valid_time: 86400
- name: Checking for existing certificates
  stat:
    path: "{{ live_certs }}"
  register: live_certs_result
- block:
    - name: Stopping HAProxy
      supervisorctl:
        name: haproxy
        state: stopped
    - name: Generating certificates
      shell: >-
        certbot certonly -n
        --standalone
        -w {{ web_root }}
        -d {{ hostname }}
        --agree-tos
        --email {{ email }}
    - name: Setting up certificate
      shell: "cat fullchain.pem privkey.pem > {{ haproxy_cert }}"
      args:
        creates: "{{ haproxy_cert }}"
        chdir: "{{ live_certs }}"
    - name: Setting certificate permission
      file:
        path: "{{ haproxy_cert }}"
        state: file
        owner: haproxy
        group: haproxy
        mode: 0600
    - name: Starting HAProxy
      supervisorctl:
        name: haproxy
        state: started
  when: not live_certs_result.stat.exists
- name: Removing default certbot cron job
  file:
    path: /etc/cron.d/certbot
    state: absent
- name: Creating proxy certbot script
  template:
    src: renew-cert.sh.j2
    dest: "{{ renew_script_path }}"
    owner: root
    group: root
    mode: 0755
- name: Creating proxy certbot cron job
  cron:
    name: certbot
    cron_file: proxy_certbot
    job: "bash {{ renew_script_path }}"
    weekday: "*"
    hour: "*/12"
    minute: "0"
    user: root
