- name: Running common HAProxy tasks
  include_role:
    name: common
    tasks_from: haproxy
- name: Restarting rsyslog service
  systemd:
    name: rsyslog
    state: restarted
  when: rsyslog_conf_result.changed
