- name: Running common HAProxy tasks
  include_role:
    name: common
    tasks_from: haproxy
- name: Restarting Syslog service
  systemd:
    name: rsyslog
    state: restarted
  when: syslog_conf_result.changed
