- name: Installing required packages
  apt:
    name:
      - python
      - python-pip
      - python3
      - python3-pip
      - supervisor
      - haproxy
      - memcached
      - rsyslog
    update_cache: yes
    cache_valid_time: 86400
    state: latest
