- name: Stopping supervisord service
  systemd:
    name: supervisor
    state: stopped
    enabled: no
- name: Running common supervisord tasks
  include_role:
    name: common
    tasks_from: supervisord
