apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    role: proxy
spec:
  containers:
  - name: nginx
    image: nginx:1.15-alpine
    ports:
    - name: default-port
      containerPort: 80
      hostPort: 8088
    - name: insecure-port
      containerPort: 80
      hostPort: 80
    - name: secure-port
      containerPort: 443
      hostPort: 443
    - name: web-port
      containerPort: 8080
      hostPort: 8080
    - name: secure-web-port
      containerPort: 4443
      hostPort: 4443
    readinessProbe:
      httpGet:
        path: /
        port: web-port
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: web-port
      initialDelaySeconds: 15
      periodSeconds: 60
    volumeMounts:
    - name: conf
      mountPath: /etc/nginx
      readOnly: true
    - name: certs
      mountPath: /certs
      readOnly: true
  volumes:
  - name: conf
    configMap:
      name: nginx
  - name: certs
    secret:
      secretName: gbf-proxy
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/master: ""
