apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    role: proxy
spec:
  containers:
  - name: nginx
    image: nginx:1.15-alpine
    ports:
    - name: default-port
      containerPort: 80
      hostPort: 8088
    - name: web-port
      containerPort: 8080
      hostPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: web-port
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: web-port
      initialDelaySeconds: 5
      periodSeconds: 30
    volumeMounts:
    - name: conf
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: conf
    configMap:
      name: nginx
