local_server_dir: "{{ playbook_dir }}/../server"
server_dir: "/opt/gbf-proxy"
server_names:
  - proxy-a
  - proxy-b

haproxy_dir: "/etc/haproxy"
haproxy_cfg: "{{ haproxy_dir }}/haproxy.cfg"
haproxy_pid: "{{ haproxy_dir }}/haproxy.pid"
haproxy_cert: "{{ haproxy_dir }}/haproxy.pem"
haproxy_sock: "{{ haproxy_dir }}/admin.sock"

nginx_conf: "{{ server_dir }}/nginx.conf"
nginx_listen: "unix:{{ server_dir }}/web.sock"

memcache_mem: 768
