- name: Initialize cloud instance
  hosts: gbf-proxy
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  pre_tasks:
    - block:
        - name: Setting facts for initialization
          set_fact:
            server_version: "{{ hostvars['localhost']['server_version'] }}"
      tags:
        - services
        - proxy
  roles:
    - init
