- import_playbook: build.yml
- name: Initialize cloud instance
  hosts: gbfproxy
  become: yes
  vars:
    server_version: "{{ hostvars['localhost']['server_version'] }}"
  vars_files:
    - vars.yml
  roles:
    - common
    - init
