apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbf-proxy-controller
  labels:
    app: gbf-proxy
    role: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbf-proxy
      role: controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gbf-proxy
        role: controller
    spec:
      containers:
      - name: gbf-proxy-controller
        image: gbf-proxy:latest
        imagePullPolicy: Never
        ports:
        - name: controller-port
          containerPort: 8000
          hostPort: 8000
        command: ["gbf-proxy", "controller", "8001", "-r", "redis:6379"]
        readinessProbe:
          httpGet:
            path: /ping
            port: controller-port
            httpHeaders:
            - name: X-Granblue-Cache-API
              value: 1
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: controller-port
            httpHeaders:
            - name: X-Granblue-Cache-API
              value: 1
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gbf-proxy-controller
  labels:
    app: gbf-proxy
    role: controller
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: gbf-proxy
    role: controller
